version: '3'

services:
  gobarber-api:
    container_name: gobarber-api
    build: .
    volumes:
      - .:/home/node/api
      - /home/node/api/node_modules
    depends_on:
      - gobarber-postgres
      - gobarber-mongo
      - gobarber-redis
    networks:
      - app-connect
    ports:
      - '3333:3333'

  gobarber-mongo:
    container_name: gobarber-mongo
    image: 'mongo'
    restart: unless-stopped
    volumes:
      - mongo-data:/data
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '27017:27017'
    networks:
      - app-connect

  gobarber-postgres:
    container_name: gobarber-postgres
    image: postgres:11
    restart: unless-stopped
    volumes:
      - postgres-data:/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    networks:
      - app-connect

  gobarber-redis:
    image: redis:alpine
    container_name: gobarber-redis
    volumes:
      - redis-data:/data
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    networks:
      - app-connect

volumes:
  postgres-data:
  mongo-data:
  redis-data:

networks:
  app-connect:
      driver: bridge
